name: WORKFLOW_BUILD
on: [push]
jobs:
  build_12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: ls -lah
    - run: sudo apt-get update && sudo apt-get -qy install git python3 wget ca-certificates xz-utils
    - run: sudo mkdir -p Wireguard
    - run: sudo ./EnvDeploy -v 6.2 -p x64 # for example
