name: WORKFLOW_BUILD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: ls -lah
    - run: cd pkgscripts-ng
    - run: mkdir -p Wireguard
    - run: pkgscripts-ng/PkgCreate.py -p apollolake -v 6.2 -S --build-opt=-J --print-log -c WireGuard
